### ISSUE TITLE
Use volumes

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/oync#45]
otherwise all retrieved changesets are lost when removing containers

**Comment by chrisnatali** [comment]
This can be configured in the docker-compose.yml with something like:

```
oync:
    image: "selcolumbia/oync:0.1"
    links:
      - "db:db"
    volumes:
      # write load directory (and all changesets) outside the container
      - ./load:/oync/load
    environment:
        OYNC_OSM_API_URL: 'http://gridmaps.org'
        OYNC_READ_TIMEOUT: 360
    command:  ./bin/run-oync.sh
```
